const fs = require('fs');
const path = 'src/data/companies.ts';

const content = `export interface CompanyMeta {
  id: string;
  name: string;
  shortName: string;
  industry: string;
  size: string;
  description: string;
  hq: string;
  globalPresence: string[];
  website?: string;
  linkedin?: string;
  color: string;
}

export const COMPANIES_META: CompanyMeta[] = [
  {
    id: "siemens",
    name: "Siemens",
    shortName: "S",
    industry: "Automation, Machinery, Manufacturing",
    size: "10,001+",
    description: "Global technology powerhouse focusing on industry, infrastructure, transport, and healthcare.",
    hq: "Germany",
    globalPresence: ["Germany", "Egypt"],
    website: "https://www.siemens.com",
    linkedin: "https://www.linkedin.com/company/siemens",
    color: "bg-teal-500",
  },
  {
    id: "capgemini",
    name: "Capgemini",
    shortName: "C",
    industry: "IT Services and IT Consulting",
    size: "10,001+",
    description: "Global leader in consulting, digital transformation, technology and engineering services.",
    hq: "France",
    globalPresence: ["France", "Egypt"],
    website: "https://www.capgemini.com",
    linkedin: "https://www.linkedin.com/company/capgemini",
    color: "bg-cyan-600",
  },
  {
    id: "cisco",
    name: "Cisco",
    shortName: "C",
    industry: "Networking Hardware",
    size: "10,001+",
    description: "Worldwide leader in IT, networking, and cybersecurity solutions.",
    hq: "United States",
    globalPresence: ["United States", "Egypt"],
    website: "https://www.cisco.com",
    linkedin: "https://www.linkedin.com/company/cisco",
    color: "bg-sky-600",
  },
  {
    id: "siemens-energy",
    name: "Siemens Energy",
    shortName: "SE",
    industry: "Energy",
    size: "10,001+",
    description: "Leading energy technology company focused on driving the energy transition.",
    hq: "Germany",
    globalPresence: ["Germany", "Egypt"],
    website: "https://www.siemens-energy.com",
    linkedin: "https://www.linkedin.com/company/siemens-energy",
    color: "bg-teal-600",
  },
  {
    id: "stmicroelectronics",
    name: "STMicroelectronics (ST)",
    shortName: "ST",
    industry: "Multinational (Design & R&D)",
    size: "10,001+",
    description: "Semiconductor manufacturer; IC design (digital, mixed-signal). Global IDM (Integrated Device Manufacturer).",
    hq: "Switzerland",
    globalPresence: ["Switzerland", "Egypt", "France", "Italy"],
    website: "https://www.st.com",
    linkedin: "https://www.linkedin.com/company/stmicroelectronics",
    color: "bg-blue-600",
  },
  {
    id: "mediatek",
    name: "MediaTek",
    shortName: "ME",
    industry: "Multinational (Design & R&D)",
    size: "10,001+",
    description: "Fabless semiconductor company designing chips for wireless, mobile, and multimedia.",
    hq: "Taiwan",
    globalPresence: ["Taiwan", "Egypt"],
    website: "https://www.mediatek.com",
    linkedin: "https://www.linkedin.com/company/mediatek",
    color: "bg-red-600",
  },
  {
    id: "brightskies",
    name: "Brightskies",
    shortName: "B",
    industry: "Software & Engineering",
    size: "501-1,000",
    description: "Technology provider and digital transformation partner for various industries.",
    hq: "Egypt",
    globalPresence: ["Egypt"],
    website: "https://brightskies.com",
    linkedin: "https://www.linkedin.com/company/brightskies",
    color: "bg-indigo-500",
  },
  {
    id: "hcltech",
    name: "HCLTech",
    shortName: "H",
    industry: "IT Services",
    size: "10,001+",
    description: "Global technology company, home to 225,000+ people across 60 countries.",
    hq: "India",
    globalPresence: ["India", "Egypt"],
    website: "https://www.hcltech.com",
    linkedin: "https://www.linkedin.com/company/hcltech",
    color: "bg-blue-800",
  },
  {
    id: "nawy",
    name: "Nawy",
    shortName: "N",
    industry: "Real Estate Tech",
    size: "201-500",
    description: "Proptech startup revolutionizing the real estate market in Egypt.",
    hq: "Egypt",
    globalPresence: ["Egypt"],
    website: "https://www.nawy.com",
    linkedin: "https://www.linkedin.com/company/nawyestate",
    color: "bg-emerald-500",
  },
  {
    id: "analog-devices",
    name: "Analog Devices (ADI)",
    shortName: "Ai",
    industry: "Multinational (Design & R&D)",
    size: "10,001+",
    description: "High-performance analog and mixed-signal integrated circuits.",
    hq: "United States",
    globalPresence: ["United States", "Egypt"],
    website: "https://www.analog.com",
    linkedin: "https://www.linkedin.com/company/analog-devices",
    color: "bg-slate-500",
  },
  {
    id: "infinilink",
    name: "InfiniLink",
    shortName: "IL",
    industry: "Engineering Services",
    size: "51-200",
    description: "Advanced design and engineering services provider.",
    hq: "Egypt",
    globalPresence: ["Egypt"],
    website: "https://www.infinilink.com",
    linkedin: "https://www.linkedin.com/company/infinilink",
    color: "bg-violet-600",
  },
  {
    id: "valeo",
    name: "Valeo",
    shortName: "V",
    industry: "Automotive Supplier",
    size: "10,001+",
    description: "Automotive supplier, partner to all automakers worldwide.",
    hq: "France",
    globalPresence: ["France", "Egypt"],
    website: "https://www.valeo.com",
    linkedin: "https://www.linkedin.com/company/valeo",
    color: "bg-green-600",
  },
  {
    id: "siemens-gamesa",
    name: "Siemens Gamesa",
    shortName: "SG",
    industry: "Renewable Energy",
    size: "10,001+",
    description: "Global leader in the renewable energy industry and wind power solutions.",
    hq: "Spain",
    globalPresence: ["Spain", "Egypt"],
    website: "https://www.siemensgamesa.com",
    linkedin: "https://www.linkedin.com/company/siemensgamesa",
    color: "bg-teal-700",
  },
  {
    id: "iss-international",
    name: "ISS INTERNATIONAL SpA",
    shortName: "ISS",
    industry: "Engineering & Consulting",
    size: "1,001-5,000",
    description: "Engineering, procurement, construction and project management services.",
    hq: "Italy",
    globalPresence: ["Italy", "Egypt"],
    website: "https://www.iss-international.it",
    linkedin: "https://www.linkedin.com/company/iss-international-spa",
    color: "bg-sky-700",
  },
  {
    id: "siemens-dis",
    name: "Siemens Digital Industries Software",
    shortName: "SDIS",
    industry: "Software",
    size: "10,001+",
    description: "Leading global provider of software solutions to drive the digital transformation of industry.",
    hq: "United States",
    globalPresence: ["United States", "Egypt"],
    website: "https://plm.automation.siemens.com",
    linkedin: "https://www.linkedin.com/company/siemens-digital-industries-software",
    color: "bg-teal-800",
  },
  {
    id: "mixel",
    name: "Mixel-Egypt",
    shortName: "MX",
    industry: "Semiconductor IP",
    size: "51-200",
    description: "Leading provider of mixed-signal IPs and MIPI IPs for mobile and enterprise markets.",
    hq: "United States",
    globalPresence: ["United States", "Egypt"],
    website: "https://mixel.com",
    linkedin: "https://www.linkedin.com/company/mixel-inc",
    color: "bg-red-500",
  }
];
`;
fs.writeFileSync(path, content, 'utf8');
console.log('companies.ts updated.');
